# Generated by Django 5.1 on 2025-11-19 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[А-ЯЁа-яё]+$', 'Фамилия должна содержать только кириллицу')], verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[А-ЯЁа-яё]+$', 'Имя должно содержать только кириллицу')], verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[А-ЯЁа-яё]+$', 'Отчество должно содержать только кириллицу')], verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
