# Generated by Django 5.1 on 2025-11-19 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Разрешены только русские буквы, пробел и дефис', regex='^[А-ЯЁа-яё\\s-]+$')], verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Разрешены только русские буквы, пробел и дефис', regex='^[А-ЯЁа-яё\\s-]+$')], verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Разрешены только русские буквы, пробел и дефис', regex='^[А-ЯЁа-яё\\s-]+$')], verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Карточка человека',
                'verbose_name_plural': 'Карточки людей',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
